### ISSUE TITLE
Navigating with Browser Safari

### ISSUE THREAD

**Issue by Quimoniz** [metricq/metricq-webview#12]
Navigating the diagram (panning, zooming, scrolling) doesn't work properly on an Apple MacBook with Browser Safari. Especially troublesome is using the MacBooks/laptops trackpad. Javascript-Event ['ongesturechange'](https://developer.apple.com/documentation/webkitjs/gestureevent) isn't triggered properly.

Regarding the meaning of ongesturechange: https://stackoverflow.com/questions/10921230/what-are-differences-between-touchmove-and-gesturechange

**Comment by tilsche** [comment]
closed in favor of #105
