### ISSUE TITLE
Show time range of last XX days/hours

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#17]
Please support rendering a given time range from now to the past. Should support several units, most importantly hours and days. When a user manually zooms/drags, the time range will use the start/end timestamps again.

- [x] Support passing this information through the url (this is the most important to support legacy chart links)
- [x] Add setting for this in the "Zeitachsen-Einstellungen"

**Comment by Quimoniz** [comment]
Parse relative time units in urls like these: https://dataheap.zih.tu-dresden.de/charts/content/metricq/#/~(cntr~(~'elab.ariel.power~'elab.diana.power)~value~30~unit~'minute*28s*29~type~'default)-

**Comment by Quimoniz** [comment]
As discussed earlier with tilsche, we will use Bootstrap's [`.nav-pills`-CSS-class](https://getbootstrap.com/docs/4.4/components/navs/#pills) to switch between tabs of

- absolute time specification inputs
- relative time specification inputs (i.e. use an input range and a dropdown)

**Comment by tilsche** [comment]
Fixed by #54
