### ISSUE TITLE
Rendering can show zero as value

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-webview#173]
When you set the canvas resolution to a high value (slider to the left-most) and the zoom speed to a very low value (slider to the left-most), and then zoom in and out, it can happen that the HTA rendering gets tricked into showing a zero as value:

query: http://localhost:8080/#.1656500494613.48*1656500604386.9*LZR.E98.0901A.B81.LA*LZR.E98.0901A.B81.LC*LZR.E98.0901A.B81.LB

![grafik](https://user-images.githubusercontent.com/130405/176424996-a2249fec-fd37-4a27-a863-2d126a35009e.png)

Slightly different zoom shows the expected graph:

![grafik](https://user-images.githubusercontent.com/130405/176425187-4a1bfe86-5f79-4e41-9048-08f1d4c4ed1a.png)

**Comment by tilsche** [comment]
Not sure this is exactly the same issue, but in general, if there are gaps - i.e. empty aggregates, then this zero is shown. This should not happen.

https://metricq.zih.tu-dresden.de/webview/#.1657469439848*1657824804732*LZR.K02.PSP00.B73
