### ISSUE TITLE
Undeterministic metric sequence in legend

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-webview#191]
It seems that the order of metrics in the legend isn't deterministic, even though the same link is used.
This causes the legend to change on reload and change the link.

For instance: https://metricq.zih.tu-dresden.de/webview/#.now-1h*now*LZR.E00.EIN01.B82.L2*LZR.E00.EIN01.B82.L3*LZR.E00.EIN02.B82.L3*LZR.E00.EIN02.B82.L2*LZR.E00.EIN01.B82.L1*LZR.E00.EIN02.B82.L1

**Comment by bmario** [comment]
Fixed in 9ca3452

**Comment by tilsche** [comment]
Seems to work in Firefox, but not in current chromium.

**Comment by bmario** [comment]
Fixed in ec58095d30c6d03638705cd3f66f0af5f722cfe8
