### ISSUE TITLE
x-axis labeling for years is broken

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-webview#195]
![grafik](https://github.com/metricq/metricq-webview/assets/130405/ac8d69af-c2ee-49b7-b3a6-4f1960bc4de8)

Link to reproduce

https://metricq.zih.tu-dresden.de/webview/#.1487443092579.2*1820283463271.2*LZR.H01.ABG01.B08*LZR.H01.ABG01.B29.MB

**Comment by Quimoniz** [comment]
I tried to address the x axis labeling issue in [this bugfix](https://github.com/metricq/metricq-webview/commit/7f78e2f2f4df8f3d5f24635ab0f5bc21dfd90be2).  I ran it through `yarn lint`, and it seems fine to me. @bmario please check on whether it (A) works? and (B) solves this problem?

**Comment by tilsche** [comment]
Fixed by #196
