### ISSUE TITLE
2024 X-axis broken

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#197]
The time axis is very broken starting 1 Jan 2024. It somehow does not show any ticks at the first(?) day after the start timestamp?!

**Comment by Quimoniz** [comment]
Hi Thomas,

I looked into this, setting a Breakpoint in with Firefox's JavaScript-Debugger. Apparently the 
[Fix#196: X-Axis-Labeling, when incrementing year, be aware of Leap Years](https://github.com/metricq/metricq-webview/pull/196) is the culprit. I noticed, the leap year check is incomplete [here in Line 207](https://github.com/metricq/metricq-webview/blob/a36fce9072dfebb9a85c01e3ac3048d540e5f06e/src/graticule.js#L207):

When we have a leap year (like 2024), the implementation adds a whole day to the first x-axis tick step - regardless of whether it's before the leap day or after.

### Suggested solutions:
- (A) wait until February 29th, 2024, then the bug will be much less noticeable.
- (B) extend the aforementioned code line 207, with it's `if condition` by adding an additional check for if it's past the leap day, e.g. `&& (2 <= stepStart.getMonth() || (1 == stepStart.getMonth() && 29 <= stepStart.getDate()))`[*]


Kind regards,
  Lars


[*] Footnote: JavaScript's Date object starts counting Months with `0`, while for the days during the month it starts counting at `1`.

**Comment by tilsche** [comment]
Thanks for the analysis. Do you mind creating a PR for solution (B)?

**Comment by tilsche** [comment]
Thanks for the PR. I've deployed it and so far it looks good in production.
