### ISSUE TITLE
X-axis shows wrong values after some scrolling

### ISSUE THREAD

**Issue by rschoene** [metricq/metricq-webview#21]
After a while of scrolling, I have a strange offset for the timestamps marked at the x-axis. The mouse-over stats provide the correct information, though.
![x-axis-bug](https://user-images.githubusercontent.com/9930030/94895228-4cc6e300-048b-11eb-988f-5d671e2c391e.png)

**Comment by rschoene** [comment]
Oh, the y-axis also shows wrong values and should peek at about 282 Watt

**Comment by Quimoniz** [comment]
Unfortunately I can not reproduce it. Please post the url to faulty version next time it comes up.
