### ISSUE TITLE
Resize canvas, mouse pointers

### ISSUE THREAD

**Issue by Quimoniz** [metricq/metricq-webview#4]
Allow for resizing the diagram-canvas in the HTML page manually with your mouse.

Also use proper mouse pointer for resizing (e.g. 'se-resize'): https://www.w3schools.com/jsref/prop_style_cursor.asp

While you are implementing changing the mouse cursor: Also implement showing an appropriate cursor when moving 'panning' the diagram along the time axis (e.g. 'grab' and 'grabbing'/'move').

Maybe also implement a 'context-menu' cursor-pointer for hovering over the gears for configuring the x-axis and y-axis.

**Comment by tilsche** [comment]
Since the canvas automatically stretches to the window size (-legend/menu) properly, there is no need for this.
