### ISSUE TITLE
Use ES6 features

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#48]
Since we use imports anyway, we can use anything from ES6. We should look through the code to identify things that can be done better by using ES6.

Note that we are not strictly limited to ES6. If something in a higher ES helps us, we can figure out if it's available enough and use it as well.

- [ ] use arrow function instead of (function (self) { ... })(this) (http://es6-features.org/#Lexicalthis)
- [ ] use method properties (http://es6-features.org/#MethodProperties)
- [ ] use classes instead of class-like functions (e.g. in data-handling, graticule)

**Comment by kinnarr** [comment]
- [ ] use arrow function instead of (function (self) { ... })(this) (http://es6-features.org/#Lexicalthis)
- [ ] use method properties (http://es6-features.org/#MethodProperties)
- [ ] use classes instead of class-like functions (e.g. in data-handling, graticule)

**Comment by tilsche** [comment]
The first point may is also (partially?) addressed by !154.

**Comment by AndyBuchwald** [comment]
> 

the last remaining selfReference is going to be removed by #153
